apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bartoszmajkowski/backend_chmurowe:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4200
